[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Haotian Zhang"
authors = [{name = "Haotian Zhang", email = "hz2475@columbia.edu"}]
dynamic = ["version", "description"]
